### ISSUE TITLE
AttributeError: 'GaussianProcess' object has no attribute 'sample'

### ISSUE THREAD

**Issue by lcx366** [treverhines/RBF#1]
When running the code in example of Gaussian process regression, the method 'sample' seems not to work well.

**Comment by treverhines** [comment]
I recently renamed the method "draw_sample" to "sample". Pull the latest version of RBF and reinstall it. What example are you running?

**Comment by lcx366** [comment]
Thanks for your reply. I indeed installed the latest version of RBF. After I replaced the ''sample" with  "draw_sample", it works well with no issues. I am running the example for Gaussian Process in this web page, http://rbf.readthedocs.io/en/latest/gauss.html. Maybe the "sample" method isn't opportunely updated in this demo.

Another question is about the PyGeoNS software. what does it mean that "In particular, if the Earth's curvature is non-negligible in your study region, then the map projection used by PyGeoNS (transverse-mercator) would not be appropriate". Does it mean that the calculation for deformation rate is based on a flat gradient instead of a spherical gradient in a certain region?

At last, it would be better if this software could evaluate these quantities including second variant strain rate, area inflation rate , shear rate and the rotation rate.

在2017-03-31 21:47:37，李春晓lcx@ynao.ac.cn写道：

I recently renamed the method "draw_sample" to "sample". Pull the latest version of RBF and reinstall it. What example are you running?

**Comment by treverhines** [comment]
Glad to hear it is working, but if "draw_sample" works then you are not using the latest version. You are pulling the master branch, right?

PyGeoNS projects the GPS station positions onto a 2-D plane using a transverse-mercator projection. If this significantly distorts the domain then the strain calculations will not be accurate.  So PyGeoNS cannot be used with, for example, a global GPS dataset. I am currently using PyGeoNS to look at strain in CA, OR, and WA, which I believe is a sufficiently small scale.

PyGeoNS calculates deformation gradients, which can easily be used to determine the metrics that you mentioned.

I also want to mention that I am still actively developing PyGeoNS. The interface and output will continue to change depending on what I am currently trying research. I anticipate that it will be another couple of months before PyGeoNS will be considered stable.
