### ISSUE TITLE
Are there ways to deal with 1D case ?

### ISSUE THREAD

**Issue by RomanLF** [treverhines/RBF#19]
Hello,

Is a way to proceed an RBF-FD method with this library on a **1D domain** such as a line of points generated by an Halton set where we could for example consider a stationnary convection diffusion equation such as,

$$
\begin{align}
U \cdot \frac{dc}{dx} - K \frac{d^2c}{dx^2} &= \delta(x-0.5) &\quad x \in \Omega = ]0,1[\\
c &= 0 &\quad x = 0, \\
&\frac{dc}{dx} = 1 &\quad x = 1
\end{align}
$$

![image](https://user-images.githubusercontent.com/74862185/145980881-e5e3fc28-5436-41e8-8fbc-a11129790b3d.png)

Do you have an hint ? I read that *min_energy_nodes* and *poisson_disc_nodes* are adapted to 2D and 3D domain. But how could 1D nodes and normals be generated ?

Thank you again providing this powerfull librairy,

Roman

**Comment by treverhines** [comment]
You are right that the node generation functions in this package are only for 2D and 3D nodes.  I imagine that `np.linspace` is all you need to get 1D nodes. The normal vectors would be [-1] and [1] for the left and right end, although your problem does not require normal vectors.

The function `rbf.pde.fd.weight_matrix` does work for 1D nodes. You should be able to set up the LHS and RHS for the problem just like in the demo scripts.

**Comment by RomanLF** [comment]
Hello,
Thank you for your help ! I managed to create the LHS and RHS problem from the exemple given in _weight_matrix_ in the docstring and it works.
Thank you for your support.

Roman
