### ISSUE TITLE
Extension for vector-valued observations

### ISSUE THREAD

**Issue by CsatiZoltan** [treverhines/RBF#23]
Since I am interested in using this library for morphing, I need to deal with vector-valued observations. One way of doing it is to perform the RBF interpolation for each component of the vector data. Another, possibly more efficient, strategy is to solve the problem at once by replacing the [right-hand side vector](https://github.com/treverhines/RBF/blob/50e4b5d5767d43b6f75b0d5c00cf6240179e19d9/rbf/interpolate.py#L200) with a matrix. Currently, `rbf.utils.assert_shape` stops me from doing it:
```python
ValueError: d is 2 dimensional but it should have 1 dimensions
````
Do you see any technical difficulty of implementing this feature? I don't know about your solvers, but `numpy.linalg.solve` can handle matrix right-hand sides.

**Comment by treverhines** [comment]
I do not see any technical difficulty to implementing that, and I agree that it should be added.

If you are just interested in RBF interpolation and you do not care about computing derivatives of the interpolant, then I would recommend using `scipy.interpolate.RBFInterpolator` (which was added to scipy in version 1.7.0).  That class is able to handle vector valued observations.

**Comment by CsatiZoltan** [comment]
Thank you. In the meantime, I found that class. Apart from containing more interpolants, does your library perform the interpolation faster (do to Cython acceleration and the partitioned solver) than SciPy's `RBFInterpolator`? All I want is morphing, no PDE solving.

**Comment by treverhines** [comment]
`scipy.interpolate.RBFInterpolator` should be faster than `rbf.interpolate.RBFInterpolant` and require less memory. So I think scipy would be the better fit for your problem.

**Comment by CsatiZoltan** [comment]
Thank you for the help. I decided to use [`RBFInterpolator`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RBFInterpolator.html) from SciPy. For future readers of this issue:
- it has the features I (currently) need
- there is [no danger](https://docs.scipy.org/doc/scipy/release.1.7.0.html#backwards-incompatible-changes) in updating SciPy to 1.7.x from the previous minor release.
- although [SciPy depends on Cython](https://docs.scipy.org/doc/scipy/dev/core-dev/index.html#dependencies), you can obtain the binaries from *PyPI* or *conda*, so the user does not need a compilation step

I close this issue because my problem has been solved. Nevertheless, I may come back to **RBF** if I need advanced features.
