### ISSUE TITLE
Reduce CPU usage by limiting number of threads

### ISSUE THREAD

**Issue by guidocioni** [treverhines/RBF#29]
Hey,
as I'd like to to use this package operationally I need some way to limit the maximum number of threads used when interpolating in order to prevent the server to fill up CPU usage with the interpolation.
For `scipy` I use something like
```python
os.environ["OPENBLAS_NUM_THREADS"] = "4"
```
but this package uses `cython` and probably the number of threads is defined there?
Thanks

**Comment by treverhines** [comment]
Does `OMP_NUM_THREADS` work for you? The multi threaded parts of RBFInterpolant are within numpy and scipy. So you would use whatever controls the threads for those packages.

**Comment by guidocioni** [comment]
> Does `OMP_NUM_THREADS` work for you? The multi threaded parts of RBFInterpolant are within numpy and scipy. So you would use whatever controls the threads for those packages.

Ok I'll give that a try! Thanks.
In theory OPENBLAS_NUM_THREADS should already act on both numpy and scipy but while using RBFInterpolant the CPU usage still spikes to 100%.

**Comment by guidocioni** [comment]
So, apparently I was doing a small mistake. Just reading my code comments from some months ago pointed me to the fact that this environmental variable has to be defined BEFORE anything related to numpy or scipy is imported. 

So, just setting 

```python
os.environ["OPENBLAS_NUM_THREADS"] = "4"
````
as first thing in the script already worked :)

Thanks again
