### ISSUE TITLE
Is there a way to avoid polynomial regularisation with weight matrices ?

### ISSUE THREAD

**Issue by RomanLF** [treverhines/RBF#31]
Hello Trever,

I read your documentation but I did not find an option to discard polynolmial regularisation with the use of `weight_matrix` function. Did I miss an option to do so ?

Best regards,
Roman

**Comment by treverhines** [comment]
Sorry for not responding. If you set `order=-1` (or set it to any negative number) then no polynomial terms would be used when computing the weight matrix.
