### ISSUE TITLE
Trying to understand how to apply Method Of Lines with RBF-FD

### ISSUE THREAD

**Issue by RomanLF** [treverhines/RBF#33]
Hello,

I read the example about conductivity and there are some things that I do not get : 
1. Why do ghost nodes boundary operator `B_free` write neuman conditions at ghost nodes position whilst free nodes express same operator as Dirichlet and interior  on `B_temp` i. e. identity for their respectives coordinates.
2. Why is differentiation matrix A applied on interior AND null flux edges ?
3. Why does state derivative write `A @ (Bsolver.solve(z)` ?
`A @ (Bsolver.solve(z)` being equivalent to `A @ inv(B) @ z` meaning : 

$$
  \frac{d \mathbf{z}}{dt} = \mathbf{A}  \mathbf{B}^{-1}\mathbf {z}
$$

I clearly do not get how the time derivative is build with the method of lines. Could you help me to understand ?

Roman

Here is Trever Hines example attached :

```python
'''
This script demonstrates using RBF-FD to solve the heat equation with spatially
variable conductivity, k(x, y). Namely,

    u_t = k_x*u_x + k*u_xx + k_y*u_y + k*u_yy

'''
import logging

import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import numpy as np
from scipy.sparse.linalg import splu
from scipy.integrate import solve_ivp

from rbf.pde.nodes import poisson_disc_nodes
from rbf.pde.fd import weight_matrix
from rbf.pde.geometry import contains
from rbf.sputils import expand_rows, expand_cols

logging.basicConfig(level=logging.DEBUG)

node_spacing = 0.1
radial_basis_function = 'phs3' # 3rd order polyharmonic spline
polynomial_order = 2
stencil_size = 30
time_evaluations = np.linspace(0, 1, 41)

vertices = np.array(
    [[-2.    ,  2.    ], [ 2.    ,  2.    ], [ 2.    , -2.    ],
     [-2.    , -2.    ], [ 1.    ,  0.    ], [ 0.9239,  0.3827],
     [ 0.7071,  0.7071], [ 0.3827,  0.9239], [ 0.    ,  1.    ],
     [-0.3827,  0.9239], [-0.7071,  0.7071], [-0.9239,  0.3827],
     [-1.    ,  0.    ], [-0.9239, -0.3827], [-0.7071, -0.7071],
     [-0.3827, -0.9239], [-0.    , -1.    ], [ 0.3827, -0.9239],
     [ 0.7071, -0.7071], [ 0.9239, -0.3827]]
    )

simplices = np.array(
    [[0 , 1 ], [1 , 2 ], [2 , 3 ], [3 , 0 ], [4 , 5 ], [5 , 6 ], [6 , 7 ],
     [7 , 8 ], [8 , 9 ], [9 , 10], [10, 11], [11, 12], [12, 13], [13, 14],
     [14, 15], [15, 16], [16, 17], [17, 18], [18, 19], [19,  4]]
    )

boundary_groups = {
    'fixed': [1, 3],
    'free': [0, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
    }

def conductivity(x):
    out = 1 + 3*(1 / (1 + np.exp(-5*x[:, 1])))
    return out

def conductivity_xdiff(x):
    # finite difference x derivative of conductivity
    delta = 1e-3
    out = (conductivity(x + [delta, 0.0]) - conductivity(x))/delta
    return out

def conductivity_ydiff(x):
    # finite difference y derivative of conductivity
    delta = 1e-3
    out = (conductivity(x + [0.0, delta]) - conductivity(x))/delta
    return out

# Generate the nodes. `groups` identifies which group each node belongs to.
# `normals` contains the normal vectors corresponding to each node (nan if the
# node is not on a boundary). We are giving the free boundary nodes ghost
# nodes to improve the accuracy of the free boundary constraint.
nodes, grp, normals = poisson_disc_nodes(
    node_spacing,
    (vertices, simplices),
    boundary_groups=boundary_groups,
    boundary_groups_with_ghosts=['free']
    )

# We will solve the heat equation by numerically integrating the state vector
# `z`. The state vector consists of:
#   - The temperature of the interior nodes at z[grp['interior']]
#   - The temperature of the fixed boundary at z[grp['boundary:fixed']]
#   - The temperature of the free boundary at z[grp['boundary:free']]
#   - The boundary condition at the free boundary at z[grp['ghosts:free']]
#
z_init = np.zeros(nodes.shape[0])
z_init[grp['boundary:fixed']] = nodes[grp['boundary:fixed'], 0]

# Create a matrix that maps the temperature at `nodes` to the state vector.
# Then create a solver for it, so we can map the state vector to the
# temperature at all nodes.

# `idx` are the indices for all nodes except the ghost nodes. The mapping to
# the state vector is just an identity mapping so we only need a stencil size
# of 1.
idx = np.hstack((grp['interior'], grp['boundary:fixed'], grp['boundary:free']))
B_temp = weight_matrix(
    x=nodes[idx],
    p=nodes,
    n=1,
    diffs=[0, 0]
    )
B_free = weight_matrix(
    x=nodes[grp['boundary:free']],
    p=nodes,
    n=stencil_size,
    diffs=[[1, 0], [0, 1]],
    coeffs=[
        normals[grp['boundary:free'], 0],
        normals[grp['boundary:free'], 1]
        ],
    phi=radial_basis_function,
    order=polynomial_order
    )

B = expand_rows(B_temp, idx, nodes.shape[0])
B += expand_rows(B_free, grp['ghosts:free'], nodes.shape[0])
B = B.tocsc()
Bsolver = splu(B)

# construct a matrix that maps the temperature at `nodes` to the time
# derivative of the state vector

# `idx` are the indices of the state vector with a non-zero time derivative
# (i.e., the elements of the state vector that are not enforcing the boundary
# conditions).
idx = np.hstack((grp['interior'], grp['boundary:free']))
A = weight_matrix(
    x=nodes[idx],
    p=nodes,
    n=stencil_size,
    diffs=[[1, 0], [2, 0], [0, 1], [0, 2]],
    coeffs=[
        conductivity_xdiff(nodes[idx]),
        conductivity(nodes[idx]),
        conductivity_ydiff(nodes[idx]),
        conductivity(nodes[idx])
        ],
    phi=radial_basis_function,
    order=polynomial_order
    )
A = expand_rows(A, idx, nodes.shape[0])
A = A.tocsc()

def state_derivative(t, z):
    return A.dot(Bsolver.solve(z))

soln = solve_ivp(
    fun=state_derivative,
    t_span=[time_evaluations[0], time_evaluations[-1]],
    y0=z_init,
    method='RK45',
    t_eval=time_evaluations
    )

## PLOTTING
# create the interpolation points
xy_grid = np.mgrid[-2.01:2.01:200j, -2.01:2.01:200j]
xy = xy_grid.reshape(2, -1).T

# create an interpolation matrix that maps the state vector to the temperature
# at `xy`. `idx` consists of indices of the state vector that are temperatures.
idx = np.hstack((grp['interior'], grp['boundary:fixed'], grp['boundary:free']))
I = weight_matrix(
    x=xy,
    p=nodes[idx],
    n=stencil_size,
    diffs=[0, 0],
    phi=radial_basis_function,
    order=polynomial_order
    )
I = expand_cols(I, idx, nodes.shape[0])

# create a mask for points in `xy` that are outside of the domain
is_outside = ~contains(xy, vertices, simplices)

fig1, ax1  = plt.subplots()
k = conductivity(xy)
k[is_outside] = np.nan
k = k.reshape(200, 200)
p = ax1.contourf(*xy_grid, k, np.linspace(1, 4, 11), cmap='viridis')

for smp in simplices:
    ax1.plot(vertices[smp, 0], vertices[smp, 1], 'k-', zorder=1)

for i, (k, v) in enumerate(grp.items()):
    ax1.scatter(nodes[v, 0], nodes[v, 1], s=10, c='C%d' % i, label=k, zorder=2)

ax1.set_aspect('equal')
ax1.set_xlim(-2.2, 2.2)
ax1.set_ylim(-2.2, 2.2)
ax1.grid(ls=':', color='k')
ax1.legend()
cbar = fig1.colorbar(p)
cbar.set_label('heat conductivity')
fig1.tight_layout()
plt.savefig('../figures/fd.n.1.png')

fig2 = plt.figure()
# create the update function for the animation. this plots the solution at time
# `time[index]`
def update(index):
    fig2.clear()
    ax2 = fig2.add_subplot(111)

    z = soln.y[:, index]
    temp = I.dot(z)
    temp[is_outside] = np.nan
    temp = temp.reshape((200, 200))

    for s in simplices:
        ax2.plot(vertices[s, 0], vertices[s, 1], 'k-')

    p = ax2.contourf(
        *xy_grid,
        temp,
        np.linspace(-2.0, 2.0, 10),
        cmap='viridis',
        extend='both'
        )

    ax2.scatter(nodes[:, 0], nodes[:, 1], c='k', s=2)
    ax2.set_title('temperature at time: %.2f' % time_evaluations[index])

    ax2.set_xlim(-2.1, 2.1)
    ax2.set_ylim(-2.1, 2.1)
    ax2.grid(ls=':', color='k')
    ax2.set_aspect('equal')
    fig2.colorbar(p)
    fig2.tight_layout()

ani = FuncAnimation(
    fig=fig2,
    func=update,
    frames=range(len(time_evaluations)),
    repeat=True,
    blit=False
    )

ani.save('../figures/fd.n.2.gif', writer='imagemagick', fps=3)
plt.show()
```

**Comment by treverhines** [comment]
Hi Roman,

I think having ghost nodes makes this example particularly confusing. I will try to answer your questions

Regarding 1 and 2: we use ghost nodes so that we can enforce both the PDE and the boundary condition at the boundary nodes, while nothing is being enforced at the ghost nodes. Even though nothing is enforced at the ghost nodes, we can still get the temperature at the _ghost nodes_ that would satisfy the free boundary condition at the  _boundary nodes_, which is what we are really computing in the `Bsolver.solve(z)` step.  That step is also giving us the temperature at the interior nodes and the boundary nodes, but those are trivially known from the state vector and hence why they have the identity mapping. So `Bsolver.solve(z)` gives us the temperature at all the nodes (ghosts, boundaries, and interior), which we dot with the matrix A to get the time derivative at the boundary and interior nodes. The time derivative at the boundary and interior nodes is then used to update their temperatures in the state vector, and a new iteration can start.

Regarding 3: you could do that. The inverse of `B` should still be sparse, although not as sparse as `B`. I don't know how big of a difference it makes.

**Comment by RomanLF** [comment]
Hello Trever,

Thank you for your answers. As I have difficulties to understand how to formalize MOL with RBF-FD framework, I will send my questions with the attached docs as the maths do not render with github :( .

[methode_des_lignes_rbf.md](https://github.com/treverhines/RBF/files/11906284/methode_des_lignes_rbf.md)
[methode_des_lignes_rbf.pdf](https://github.com/treverhines/RBF/files/11906286/methode_des_lignes_rbf.pdf)

Thank for your support,
Roman

**Comment by treverhines** [comment]
I think maybe the confusion is in eq. 6. When you have Neumann boundary conditions, you would not formulate the MOL problem as  
$\mathbf{u}_t = \mathbf{Mu}.$

Instead, you would define a state vector $\mathbf{z}$ that consists of the temperature at the interior nodes, temperature at the dirichlet boundaries nodes, and the boundary conditions at the neumann nodes (i.e., 0). So something like $\mathbf{z} = [\mathbf{u}(x_{interior}), \mathbf{u}(x_{dirichlet}), \frac{d\mathbf{u}}{dn}(x_{neumann})] = [\mathbf{u}(x_{interior}), \mathbf{g}, \mathbf{0}]$. Following your question, I am also assuming we are not dealing with ghost nodes here. The MOL problem would then be formulated as 
$\mathbf{z}_t = \mathbf{Mz}.$
The matrix $\mathbf{M}$ would be $\mathbf{A}\mathbf{B}^{-1}$. The matrix $\mathbf{B}^{-1}$ maps $\mathbf{z}$ to the temperature at all the nodes (interior and boundaries). The matrix $\mathbf{A}$ maps the temperatures at all the nodes to the time derivative of $\mathbf{z}$, which is zero at the indices corresponding to the dirichlet and neumann boundaries.

This formulation is not specific to RBF-FD. The matrix $\mathbf{M}$ could have also been constructed with traditional finite differences. Maybe it would help if you looked for other examples online of using scipy's ODE solver to solve the diffusion equation with regular finite differences.

**Comment by RomanLF** [comment]
Ok following what you say : 

- State vector $\mathbf{z} = [ \mathbf{u}(x_i), \mathbf{u}(x_d), \frac{d \mathbf{u}}{d \mathbf{n}}(x_n)]$
- temperature vector $\mathbf{u} = [\mathbf{u}(x_i), \mathbf{u}(x_d), \mathbf{u}(x_n)]$
- Mapping $\mathbf{u}$ towards state vector : $\mathbf{B}\mathbf{u} = \mathbf{z}$ : identity is applied everywhere except where neuman condition is prescribed.
  - Consequently $u = \mathbf{B}^{-1}z$
- we aim to build $\mathbf{z}_t = \mathbf{M}{\mathbf{z}}$
  - and $\mathbf{A}\mathbf{u} = [\mathbf{L} u(x_i), \mathbf{0}(x_d), \mathbf{0}(x_n)]$ . It applies interior operator $\mathbf{L}$ but does not act on boundaries which is handled by $\mathbf{Bu}$
  - Hence  $\mathbf{z}_t = AB^{-1}{\mathbf{z}}$ boundaries and interior conditions are prescribed.

Similarly with ghost nodes, $\mathbf{z} = [ \mathbf{u}(x_i), \mathbf{u}(x_d), \mathbf{u}(x_n), \frac{d \mathbf{u}}{d \mathbf{n}}(x_g|x_n)]$

with last term being neuman conditions evaluated on $x_n$ but prescribed on the $x_d$ nodes correct me if I am wrong.

Thank you for your answer !
Roman

**Comment by RomanLF** [comment]
Hello Trever,

1. In your stationary example you impose interior operator evaluated on $x_n$ boundary node i.e. $\mathbf{L}(x_n)$, to then evaluate $\mathbf{L}(x_n)  \mathbf{u}(x_g) = \mathbf{f}_g$ and hence enforce ghost nodes with interior operators.
   In this transient example and also in wave movement problem, you enforce $\mathbf{u}_n$ to interior conditions and $\mathbf{u}_g$ to Neumann conditions is there a reason ? Would it be possible to do it the other way ?

Here is how I would sum up your implementations from the examples :

- Stationary : $\mathbf{A} \mathbf{u} = [\mathbf{L}(x_i) \mathbf{u}_i, Id(x_d) \mathbf{u}_d, \mathbf{B}_n(x_n) \mathbf{u}_n, \mathbf{L}(x_n)\mathbf{u}_g]$ and especially boundary conditions $\mathbf{C}{\mathbf{u}} = [ Id(x_d)\mathbf{u}_d, \mathbf{B}_n(x_n) , \mathbf{u}_n, \mathbf{L}(x_n)\mathbf{u}_g]$, with $\mathbf{C}$ agglomerated boundary operator (to avoid confusion with $\mathbf{B}$ state vector mapping).

- Transient : $\mathbf{A} \mathbf{u} = [\mathbf{L}(x_i) \mathbf{u}_i, \mathbf{0} \mathbf{u}_d, \mathbf{L}(x_n) \mathbf{u}_n, \mathbf{0} \mathbf{u}_g]$,  with boundaries $\mathbf{C}\mathbf{u} = [Id(x_d)\mathbf{u_d}, Id(x_n)\mathbf{u_n}, \mathbf{B}_n(x_n)\mathbf{u}_g]$.

2. In the case you apply interior operator on ghost nodes. Where would the conductivity field $\mathbf{K}$ would be evaluated ? On boundary $\mathbf{K}(x_n)$ ? Where would the conductivity field $\mathbf{K}$ would be evaluated ? On boundary $\mathbf{K}(x_n)$ ?

Best regards,
Roman
