### ISSUE TITLE
Generating weight matrices for different derivatives simultaneously

### ISSUE THREAD

**Issue by apt-get-nat** [treverhines/RBF#34]
Is there a way to get fd.weight_matrix to produce matrices for, say, [1,0] and [0,1] at the same time? Not as a sum, but as two different operations. Under the hood, it would just be different right hand sides for the same core RBF matrix-vector system for each stencil. Solving against multiple right hand sides as a tall, skinny matrix should be much faster than re-inverting the system in multiple fd.weight_matrix calls.

See e.g. Appendix B of Flyer, Barnett & Wicker 2016 https://doi.org/10.1016/j.jcp.2016.02.078 where they do it this way in their MATLAB implementation.

**Comment by treverhines** [comment]
There is not a way to do that, but I like the idea. I am trying to think of what the usage should look like. It seems like this should be implemented in a new function called `weight_matrices`, where specifying `diffs=[[1, 0], [0, 1], [[2, 0], [0, 2]]]` would be interpreted as requesting the matrices for d/dx, d/dy, and the Laplacian.

I am pretty immersed in another project right now, so I dont know when I will get around to this.

**Comment by treverhines** [comment]
i added the argument `sum_terms` to `weight_matrix`. If you set it to false, the function will return the rbf-fd weight matrix for each term.

**Comment by apt-get-nat** [comment]
That's awesome, thank you!
