### ISSUE TITLE
Some windows installations do not have a c compiler, please allow for python only execution.

### ISSUE THREAD

**Issue by NelisW** [treverhines/RBF#6]
RBF requires a c compiler to be present during  installation and also during routine execution after installation (required for sympy symbolic to executable code).  Building a binary wheel allowed me to install RBF on another computer, but then during execution it still required a compiler to build code.

Please provide the option to use Python only for users without c compilers (e.g., on Windows). Something like

if ccompiler:
    ufuncify(x_sym+c_sym+(_EPS,), expr,backend='numpy')
else:
    sympy.lambdify(x_sym+c_sym+(_EPS,), expr, modules=['numpy'])

thanks and keep up the good work!

**Comment by treverhines** [comment]
@NelisW I added the function `rbf.basis.set_symbolic_to_numeric_method` (https://rbf.readthedocs.io/en/latest/basis.html#rbf.basis.set_symbolic_to_numeric_method). Which controls whether `ufuncify` or `lambdify` is used.  You will need to call `rbf.basis.set_symbolic_to_numeric_method("lambdify")` at the start of your script if a c compiler is not available.
