### ISSUE TITLE
Discrepancy with scipy Rbf interpolation when using Gaussian basis

### ISSUE THREAD

**Issue by iraikov** [treverhines/RBF#9]
Hello,

I get very different results when interpolating with RBF and scipy.Rbf using gaussian basis.
I noticed that RBF and Scipy use different definition for what is called 'gaussian' basis, but even if I use the scipy basis expression in RBF, the results are different. The code below shows the different. Any help is much appreciated.

```

# coding: utf-8

# In[1]:


import random
import numpy as np
from scipy.interpolate import Rbf
import rbf
from rbf.interpolate import RBFInterpolant
from rbf.pde.nodes import poisson_disc_nodes
import matplotlib.pyplot as plt
from matplotlib import cm


# In[5]:


grid_spacing     = 40.0
peak = 10.0

area_dimension = 100 + float(grid_spacing) / 2.0
vert = np.array([[-area_dimension,-area_dimension],[-area_dimension,area_dimension],
                    [area_dimension,area_dimension],[area_dimension,-area_dimension]])
smp = np.array([[0,1],[1,2],[2,3],[3,0]])


nodes, groups, _ = poisson_disc_nodes(float(grid_spacing), (vert, smp))

fig, ax = plt.subplots()
ax.plot(nodes[:, 0], nodes[:, 1], 'ko', markersize=4)


# In[7]:


x_obs = nodes
u_obs = peak * np.ones(len(x_obs))

ip2  = Rbf(x_obs[:,0], x_obs[:,1], u_obs, function='gaussian', sigma=0.1,  epsilon=grid_spacing/2.71828)

area_x = np.arange(-100, 100, 1)
area_y = np.arange(-100, 100, 1)

xx, yy = np.meshgrid(area_x, area_y, indexing='ij')
zz2 = ip2(xx, yy)

plt.pcolor(xx, yy, zz2,cmap=cm.jet)
plt.scatter(x_obs[:,0], x_obs[:,1], u_obs, cmap=cm.jet)
ax = plt.gca()
ax.set_aspect('equal')


# In[9]:


x_obs = nodes
u_obs = peak * np.ones(len(x_obs))


from rbf.basis import *
r = get_r()
eps = get_eps()
ga_expr = sympy.exp(-(r/eps)**2)
ga = RBF(ga_expr)

ip1  = RBFInterpolant(x_obs, u_obs, phi=ga, sigma=0.1, eps=grid_spacing/2.)

arena_x = np.arange(-100, 100, 1)
arena_y = np.arange(-100, 100, 1)

xx, yy = np.meshgrid(arena_x, arena_y)
coords = np.column_stack((xx.ravel(), yy.ravel()))
zz1 = ip1(coords)
plt.pcolor(xx, yy, zz1.reshape(xx.shape), cmap=cm.jet)
plt.scatter(x_obs[:,0], x_obs[:,1], u_obs, cmap=cm.jet)
ax = plt.gca()
ax.set_aspect('equal')

```

**Comment by treverhines** [comment]
Hi Ivan. There are two reasons why you are seeing a difference between `scipy.Rbf` and `RBFInterpolant`:

1) `scipy.Rbf` does not include polynomial basis functions in the interpolant. The default behavior for `RBFInterpolant` is to include a constant and linear term in addition to the radial basis functions. So if there is a constant offset or linear trend in the data, `RBFInterpolant` will be able to accurately describe it.  In your example, your observed values are a constant `10.0`, and consequently the values returned by `RBFInterpolant` are also all `10.0`. You can control the order of the added polynomial terms with the `order` kwarg. Set `order=-1` to prevent any polynomial terms from being added. It is common practice to include these polynomial terms for RBF interpolation, and the fact that they are not included in `scipy.Rbf` is a deficiency that is currently being addressed (  https://github.com/scipy/scipy/issues/9904)   

2)  You are calling `scipy.Rbf` with `sigma` as a kwarg, and it is being silently ignored. The argument you are looking for is `smooth`. Unfortunately, it looks like there is a sign error in the implementation of `smooth` in `scipy.Rbf` and so you will need to use negative values for it.  It seems like using `sigma=0.1` for `RBFInterpolant` has the same effect as using `smooth=-0.1**2` for `scipy.Rbf`. 

So to get the two interpolation functions to produce the same results, you will need to make the following modifications:

`ip2  = Rbf(x_obs[:,0], x_obs[:,1], u_obs, function='gaussian', smooth=-(0.1)**2, epsilon=grid_spacing/2.71828)`

and

`ip1  = RBFInterpolant(x_obs, u_obs, phi=ga, sigma=0.1, eps=grid_spacing/2.71828, order=-1)`

**Comment by iraikov** [comment]
Hi Trever,

Thanks for the quick response. Indeed, after making your suggested changes, the differences disappeared.
